# Generated by Django 3.1.4 on 2020-12-26 00:55

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Application',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('applicant_id', models.IntegerField()),
                ('job_id', models.IntegerField()),
                ('resume', models.CharField(max_length=10)),
                ('cover_letter', models.TextField()),
            ],
        ),
    ]
