# Generated by Django 3.1.4 on 2020-12-29 03:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='application',
            name='timestamp',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
