# Generated by Django 3.1.4 on 2020-12-23 03:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employer', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='profile',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
